### ISSUE TITLE
タイピングによる描画の位置調整

### ISSUE THREAD

**Issue by Harutaka-Tsujino** [human-osaka-game-2018/LethalBlast#11]
αにむけてタイピングしている文字などの位置を調整する

**Comment by taishi-matsumura** [comment]
@Harutaka-Tsujino 終わってるならcloseしておいて下さい。
コミットと紐付いてないので残念ながらどのコミットで完了したのかわかりませんが、仕方ないですね。
今後、気を付けましょう。

**Comment by Harutaka-Tsujino** [comment]
了解です
以後気を付けます
